# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f204c2875b6d9b9a3f7c2fc7cb3b2d826715295d3d47481f36370ef601d2f1d166e27f458576bc56b0c7c70ac548cafacba78deeb93776aab576ad8a83a9404d

test:
  secret_key_base: ef7ca9d80f6dcd649d5b2bdfce91fc0c42725c12ae457620b70e3179e4358544162dfdb63e474d2c9f288d069740301a9a0864d6868d583befab001eb91d1791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
